var endpoint;

// Register a Service Worker.
navigator.serviceWorker.register('sw_pa.js')  //service-worker.js
.then(function(registration) {
  // Use the PushManager to get the user's subscription to the push service.
  return registration.pushManager.getSubscription()
  .then(function(subscription) {
    // If a subscription was found, return it.
    if (subscription) {
      return subscription;
    }

    // Otherwise, subscribe the user (userVisibleOnly allows to specify that we don't plan to
    // send notifications that don't have a visible effect for the user).
    return registration.pushManager.subscribe({ userVisibleOnly: true });
  });
}).then(function(subscription) {
  endpoint = subscription.endpoint;

  // Show curl command to send the notification on the page.
  document.getElementById('curl').textContent = 'curl -H "TTL: 60" -X POST ' + endpoint;

  // Send the subscription details to the server using the Fetch API.
  fetch('https://maps.dwd.de/geoserver/dwd/wms/?REQUEST=GetFeatureInfo&SERVICE=WMS&SRS=EPSG%3A4326&STYLES=&TRANSPARENT=true&VERSION=1.1.1&FORMAT=image%2Fpng&BBOX=4.383544921875001%2C47.931066347509784%2C13.172607421875002%2C52.16045455774706&HEIGHT=600&WIDTH=800&LAYERS=dwd%3AWarnungen_Gemeinden_vereinigt&QUERY_LAYERS=dwd%3AWarnungen_Gemeinden_vereinigt&INFO_FORMAT=text%2Fjavascript&PROPERTYNAME=EVENT%2CONSET%2CEXPIRES%2CSENT&FEATURE_COUNT=50&X=392&Y=328&callback=parseResponse&_=1513179859204', {  //  https://fcc-weather-api.glitch.me/api/current?lat=48.4&lon=10.9
    method: 'get',  //post
    headers: {
      'Content-type': 'application/json'
    },
    //body: JSON.stringify({
    //  endpoint: subscription.endpoint,
    //}),
  });
});

document.getElementById('doIt').onclick = function() {
  var delay = document.getElementById('notification-delay').value;
  var ttl = document.getElementById('notification-ttl').value;

  // Ask the server to send the client a notification.
  // This is for testing purposes, in a real application the notifications will be
  // directly generated by the server without the user asking for it (otherwise, what
  // would be the point?).
  fetch('./sendNotification?endpoint=' + endpoint + '&delay=' + delay +
        '&ttl=' + ttl,
    {
      method: 'post',
    }
  );
};
